FROM alpine:3.6

MAINTAINER isystk

# apacheのインストール
RUN apk update && \
    apk add --no-cache apache

# ポート設定
EXPOSE 80 443

RUN mkdir -p /run/apache

# フォアグラウンドでnginx実行
CMD nginx -g "daemon off;"
