FROM alpine:3.6

MAINTAINER isystk

# apacheのインストール
RUN apk update && \
    apk add --no-cache apache2

# ポート設定
EXPOSE 80 443

RUN mkdir -p /run/apache2

# フォアグラウンドでapache実行
CMD apache -g "daemon off;"
