FROM alpine:latest

MAINTAINER isystk

# apacheのインストール
RUN \
  apk update && \
	apk add mysql mysql-client && \
	addgroup mysql mysql

# timezoneをAsia/Tokyoに設定する
RUN apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    apk del tzdata

# ポート設定
EXPOSE 3306
