FROM alpine:3.6

MAINTAINER isystk

# apacheのインストール
RUN \
  apk update && \
	apk add mysql mysql-client && \
	addgroup mysql mysql && \

# ポート設定
EXPOSE 3306

RUN mkdir -p /run/apache2

# フォアグラウンドでapache実行
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
