version: '3'

services:
  
  apache:
    image: wordpress/apache
    container_name: wordpress-apache
    build:
      context: "./apache"
      dockerfile: "Dockerfile"
    ports:
     - "80:80"
     - "443:443"
    restart: always
    volumes:
     - ./apache/conf.d:/etc/apache2/conf.d
     - ./apache/ssl:/etc/apache2/ssl
     - ./apache/logs:/var/log/apache2
     - ../htdocs:/var/www/html
     - ../src:/var/www/html/wp-content/themes/mytheme

  php:
    image: wordpress/php
    container_name: wordpress-php
    build:
      context: "./php"
      dockerfile: "Dockerfile"
    restart: always
    volumes:
     - ./php/logs:/var/log/php
     - ../htdocs:/var/www/html
     - ../src:/var/www/html/wp-content/themes/mytheme

  mysql:
    image: wordpress/mysql
    container_name: wordpress-mysql
    build:
      context: "./mysql"
      dockerfile: "Dockerfile"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
     - "3306:3306"
    restart: always
    volumes:
     - ./mysql/conf.d:/etc/mysql/conf.d
     - wordpress-db-store:/var/lib/mysql
     - ./mysql/logs:/var/log/mysql

  phpmyadmin:
    image: wordpress/phpmyadmin
    container_name: wordpress-phpmyadmin
    build:
      context: "./phpmyadmin"
      dockerfile: "Dockerfile"
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    volumes:
      - "./phpmyadmin/sessions:/sessions"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: wordpress-mailhog
    ports:
      - 8025:8025
      - 25:1025


volumes:
  wordpress-db-store: