version: '3'

services:
  
  apache:
    image: ${PROJECT_NAME}/apache
    build:
      context: "./apache"
      dockerfile: "Dockerfile"
    ports:
     - "80:80"
     - "443:443"
    restart: always
    volumes:
     - ./apache/conf.d:/etc/apache2/conf.d
     - ./apache/ssl:/etc/apache2/ssl
     - ./apache/logs:/var/log/apache2
     - ../public:/var/www/html
    depends_on:
      - php

  php:
    image: ${PROJECT_NAME}/php
    build:
      context: "./php"
      dockerfile: "Dockerfile"
    volumes:
      - ../public:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: ${PROJECT_NAME}/mysql
    build:
      context: "./mysql"
      dockerfile: "Dockerfile"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
     - "3306:3306"
    restart: always
    volumes:
     - ./mysql/conf.d:/etc/mysql/conf.d
     - ./mysql/data:/var/lib/mysql
     - ./mysql/logs:/var/log/mysql
  #        #DBの実体をおいておく
  #   - ./mysql/init:/docker-entrypoint-initdb.d
  #        #MySQL初回起動時の走らせたいsqlとかshとかを渡すため

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=test
      - PMA_PASSWORD=test
    depends_on:
      - mysql