version: '3'

services:
  
  apache:
    image: ${PROJECT_NAME}/apache
    build:
      context: "./apache"
      dockerfile: "Dockerfile"
    ports:
     - "80:80"
     - "443:443"
    restart: always
    volumes:
     - ./apache/conf.d:/etc/apache2/conf.d
     - ./apache/ssl:/etc/apache2/ssl
     - ./apache/logs:/var/log/apache2
     - ../public:/var/www/html
    networks:
     - frontend
     - backend

  php:
    image: ${PROJECT_NAME}/php
    build:
      context: "./php"
      dockerfile: "Dockerfile"
    restart: always
    volumes:
     - ./php/logs:/var/log/php
     - ../public:/var/www/html
    networks:
     - backend

  mysql:
    image: ${PROJECT_NAME}/mysql
    build:
      context: "./mysql"
      dockerfile: "Dockerfile"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
     - "3306:3306"
    restart: always
    volumes:
     - ./mysql/conf.d:/etc/mysql/conf.d
     - ./mysql/data:/var/lib/mysql
     - ./mysql/logs:/var/log/mysql
    networks:
     - backend

  phpmyadmin:
    image: ${PROJECT_NAME}/phpmyadmin
    build:
      context: "./phpmyadmin"
      dockerfile: "Dockerfile"
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    volumes:
      - "./phpmyadmin/sessions:/sessions"
    networks:
     - backend

networks:
  frontend:
    external: true
  backend:
    external: true